### PR TITLE
Fix 148 - Custom IMU Orientation

### PR DESCRIPTION
**Pull request by legoabram**
This is an extension of the fix_148 branch made by superjax https://github.com/rosflight/firmware/pull/252. I figured that degrees made more sense in this context, but there wasn't a conversion to radians yet. I also made some organization changes to make it match conventions I saw elsewhere in the code base.

### CODE REVIEW

**Comment by superjax** [comment]
Hey @legoabram!

I just updated this to rebase from the current `master`.  Can you check and make sure that the rebase didn't change anything?  It looks good from my end, it just needs to be validated on hardware before merging into master.  (both fixedwing and multirotors)

**Comment by legoabram** [comment]
Sounds good to me. I'll double check the rebase tomorrow. However, I don't have any access to a multirotor. Would anyone at the MAGICC lab be available to help me test this on one in the next couple days?

**Comment by superjax** [comment]
Yeah, I can try to fly it soon.

**Comment by superjax** [comment]
Thanks!  Sorry this took so long!

**Pull request merged**
