### PR TITLE
GPS API and Aux Command Support

### PR DESCRIPTION
**Pull request by superjax**
- Allows user to supply raw PWM to all 14 outputs
- Adds plumbing for a GPS receiver but doesn't actually implement one.

### CODE REVIEW

**Comment by plusk01** [comment]
What is the timeline of this branch? https://github.com/rosflight/rosflight/commit/8289ced2836c56a1a3c9b1a03313ee51a762273c was comitted to master, but relies on this PR.

**Comment by superjax** [comment]
I'm so sorry.  I did not mean to merge GPS into `rosflight` `master`.

I'm going to remove the GPS functionality because it has a subtle bug, but leave the API.  That way they are synced up.

**Comment by superjax** [comment]
@dpkoch, could you look through this as soon as you can?

**Comment by plusk01** [comment]
Thanks!

**Pull request merged**
