### PR TITLE
Updated mavlink_send_status to work with the updated status message. …

### PR DESCRIPTION
**Pull request by len0rd**
…Control mode enum should now be able to display passthrough/angle/rate, instead of just passthrough/rate. Couldnt update mavlink_c submodule since the new headers havent been generated yet.

### CODE REVIEW

**Comment by superjax** [comment]
Something is wrong with the way you are packing the status message (check the output of the travis build).  I bet you forgot to update the mavlink submodule

**Comment by len0rd** [comment]
@superjax Right, the mavlink_c repository hasn't autogenerated the new headers yet, so I don't think I can fix that yet.

**Comment by len0rd** [comment]
Also this fix corresponds to Issue #182

**Comment by superjax** [comment]
This was superseded by #215

**Pull request closed without merging**
