### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by dpkoch**
Here's what I'm thinking for the documentation. I decided to just put it on readthedocs for now; we can always move it later if we want to. You can see a live demo at http://docs.rosflight.org/en/documentation/ (once it's all merged in you'll be able to get there straight from docs.rosflight.org).

I also tweaked the outline a bit and posted it in #122. Let me know what you think.

### CODE REVIEW

**Comment by superjax** [comment]
Sorry about the build error.  That was some half-finished work I accidentally pushed.  That's all on another branch I'm working on.

**Comment by superjax** [comment]
Hey guys, I have a draft for the core of the documentation.  I would really love it if someone would go through and make some suggestions to help improve what I wrote.

**Comment by dpkoch** [comment]
@superjax I've finished all the pages now. They may not be perfect, but unless you catch any glaring errors I say we merge them in and call it good enough for release. The readthedocs page will by default show whatever's on the latest master anyway, so we can continue editing the documentation even between releases.

**Comment by superjax** [comment]
I like it!

**Pull request merged**
